USE frozen_food_business;

-- 1. How many total orders are there?
SELECT COUNT(*) AS total_orders
FROM Orders;

-- 2. How many customers are there?
SELECT COUNT(*) AS total_customers
FROM Customers;

-- 3. How many products are available?
SELECT COUNT(*) AS total_products
FROM Products;

-- 4. How many product categories are there?
SELECT COUNT(*) AS total_categories
FROM Categories;

-- 5. How many sales channels are there?
SELECT COUNT(*) AS total_channels
FROM Sales_Channels;

-- 6. What is the total revenue?
SELECT SUM(quantity * unit_price) AS total_revenue
FROM Order_Items;

-- 7. What is the total quantity of products sold?
SELECT SUM(quantity) AS total_units_sold
FROM Order_Items;

-- 8. What is the average selling price of all products?
SELECT AVG(selling_price) AS average_selling_price
FROM Products;

-- 9. What is the highest selling price?
SELECT MAX(selling_price) AS highest_price
FROM Products;

-- 10. What is the lowest selling price?
SELECT MIN(selling_price) AS lowest_price
FROM Products;

-- 11. How many orders were placed through each sales channel?
SELECT
    sc.channel_name,
    COUNT(o.order_id) AS total_orders
FROM Orders o
JOIN Sales_Channels sc
    ON o.channel_id = sc.channel_id
GROUP BY sc.channel_name
ORDER BY total_orders DESC;

-- 12. How many orders were placed by each customer?
SELECT
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM Orders o
JOIN Customers c
    ON o.customer_id = c.customer_id
GROUP BY c.customer_name
ORDER BY total_orders DESC;

-- 13. How many products are in each category?
SELECT
    c.category_name,
    COUNT(p.product_id) AS total_products
FROM Products p
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name;

-- 14. How many units of each product were sold?
SELECT
    p.product_name,
    SUM(oi.quantity) AS units_sold
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY units_sold DESC;

-- 15. What is the total revenue generated by each product?
SELECT
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- 16. What is the total revenue generated by each category?
SELECT
    c.category_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_revenue DESC;

-- 17. What is the total revenue generated by each sales channel?
SELECT
    sc.channel_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Orders o
    ON oi.order_id = o.order_id
JOIN Sales_Channels sc
    ON o.channel_id = sc.channel_id
GROUP BY sc.channel_name
ORDER BY total_revenue DESC;

-- 18. What is the average order value for each sales channel?
SELECT
    sc.channel_name,
    SUM(oi.quantity * oi.unit_price)
    / COUNT(DISTINCT o.order_id) AS average_order_value
FROM Order_Items oi
JOIN Orders o
    ON oi.order_id = o.order_id
JOIN Sales_Channels sc
    ON o.channel_id = sc.channel_id
GROUP BY sc.channel_name;

-- 19. What is the average selling price for each category?
SELECT
    c.category_name,
    AVG(p.selling_price) AS average_price
FROM Products p
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name;

-- 20. What is the total production cost for each product?
SELECT
    p.product_name,
    SUM(oi.quantity * pc.cost_per_unit) AS total_production_cost
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Production_Costs pc
    ON oi.product_id = pc.product_id
GROUP BY p.product_name
ORDER BY total_production_cost DESC;

-- 21. Which product generated the highest revenue?
SELECT
    p.product_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 1;

-- 22. Which product has the highest number of units sold?
SELECT
    p.product_name,
    SUM(oi.quantity) AS units_sold
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY units_sold DESC
LIMIT 1;

-- 23. Which category generated the highest revenue?
SELECT
    c.category_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Categories c
    ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_revenue DESC
LIMIT 1;

-- 24. Which sales channel generated the highest revenue?
SELECT
    sc.channel_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM Order_Items oi
JOIN Orders o
    ON oi.order_id = o.order_id
JOIN Sales_Channels sc
    ON o.channel_id = sc.channel_id
GROUP BY sc.channel_name
ORDER BY total_revenue DESC
LIMIT 1;

-- 25. Calculate gross profit for each product.
SELECT
    p.product_name,
    SUM(
        (oi.quantity * oi.unit_price)
        - (oi.quantity * pc.cost_per_unit)
    ) AS gross_profit
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Production_Costs pc
    ON oi.product_id = pc.product_id
GROUP BY p.product_name
ORDER BY gross_profit DESC;

-- 26. Which product generated the highest gross profit?
SELECT
    p.product_name,
    SUM(
        (oi.quantity * oi.unit_price)
        - (oi.quantity * pc.cost_per_unit)
    ) AS gross_profit
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Production_Costs pc
    ON oi.product_id = pc.product_id
GROUP BY p.product_name
ORDER BY gross_profit DESC
LIMIT 1;

-- 27. Calculate profit margin for each product.
SELECT
    p.product_name,
    (
        SUM(
            (oi.quantity * oi.unit_price)
            - (oi.quantity * pc.cost_per_unit)
        )
        / SUM(oi.quantity * oi.unit_price)
    ) * 100 AS profit_margin
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Production_Costs pc
    ON oi.product_id = pc.product_id
GROUP BY p.product_name
ORDER BY profit_margin DESC;

-- 28. Which category has the highest profit margin?
SELECT
    c.category_name,
    (
        SUM(
            (oi.quantity * oi.unit_price)
            - (oi.quantity * pc.cost_per_unit)
        )
        / SUM(oi.quantity * oi.unit_price)
    ) * 100 AS profit_margin
FROM Order_Items oi
JOIN Products p
    ON oi.product_id = p.product_id
JOIN Categories c
    ON p.category_id = c.category_id
JOIN Production_Costs pc
    ON oi.product_id = pc.product_id
GROUP BY c.category_name
ORDER BY profit_margin DESC
LIMIT 1;

-- 29. What are the total expenses by expense type?
SELECT
    expense_type,
    SUM(amount) AS total_expense
FROM Expenses
GROUP BY expense_type
ORDER BY total_expense DESC;

-- 30. What is the net profit of the business?
SELECT
    revenue.total_revenue
    - revenue.total_production_cost
    - expenses.total_expenses AS net_profit
FROM
(
    SELECT
        SUM(oi.quantity * oi.unit_price) AS total_revenue,
        SUM(oi.quantity * pc.cost_per_unit) AS total_production_cost
    FROM Order_Items oi
    JOIN Production_Costs pc
        ON oi.product_id = pc.product_id
) revenue
CROSS JOIN
(
    SELECT
        SUM(amount) AS total_expenses
    FROM Expenses
) expenses;
